import { Hospital, Siren, Scissors, ShoppingCart } from 'lucide-react'

export const TIPOS = [
  { valor: 'todos',              label: 'Todos' },
  { valor: 'Veterinaria',        label: 'Veterinaria' },
  { valor: 'Veterinaria 24/7',   label: 'Urgencia 24/7' },
  { valor: 'Peluquería / Spa',   label: 'Peluquería' },
  { valor: 'Tienda de mascotas', label: 'Tienda de mascotas' },
]

export const TIPO_COLOR = {
  'Veterinaria':        '#7e6492',
  'Veterinaria 24/7':   '#c0392b',
  'Peluquería / Spa':   '#e07b54',
  'Tienda de mascotas': '#4a90a4',
}

export const TIPO_ICON = {
  'Veterinaria':        Hospital,
  'Veterinaria 24/7':   Siren,
  'Peluquería / Spa':   Scissors,
  'Tienda de mascotas': ShoppingCart,
}

export const COMUNAS = [
  'Todas',
  'Ancud',
  'Castro',
  'Puerto Montt',
  'Maullin',
  'Llanquihue',
  'Los Muermos',
  'Calbuco',
  'Frutillar',
  'Puerto Varas'
]

export const servicios = [
  {
    id: 1,
    tipo: 'Veterinaria',
    nombre: 'Clínica VetCare',
    descripcion: 'Clínica veterinaria con más de 15 años de experiencia en medicina general, cirugía y especialidades. Atención personalizada para perros, gatos y animales exóticos.',
    direccion: 'Av. Providencia 1234, Providencia',
    comuna: 'Providencia',
    telefono: '+56 2 2345 6789',
    wsp: '56923456789',
    web: 'www.vetcare.cl',
    instagram: 'vetcare_cl',
    facebook: 'VetCareCL',
    horario: 'Lun–Vie 9:00–19:00 · Sáb 9:00–14:00',
    promociones: [
      { id: 1, titulo: '20% en consultas este mes', descripcion: 'Descuento válido en consulta general para nuevos pacientes durante mayo 2026.' },
      { id: 2, titulo: 'Vacunación anual con 30% off', descripcion: 'Incluye vacuna polivalente y antirrábica. Consultar disponibilidad.' },
    ],
  },
  {
    id: 2,
    tipo: 'Urgencia 24/7',
    nombre: 'Hospital Animal Sur',
    descripcion: 'Centro de urgencias veterinarias disponible las 24 horas del día, los 7 días de la semana. Equipado con UCI, laboratorio y cirugía de emergencia.',
    direccion: 'Gran Avenida 5678, San Miguel',
    comuna: 'San Miguel',
    telefono: '+56 2 2987 6543',
    wsp: '56929876543',
    web: 'www.hospitalanimalsur.cl',
    instagram: 'hospitalanimalsur',
    facebook: 'HospitalAnimalSur',
    horario: 'Abierto 24/7 todos los días',
    promociones: [],
  },
  {
    id: 3,
    tipo: 'Peluquería',
    nombre: 'Grooming Express',
    descripcion: 'Servicio de peluquería y estética canina y felina. Baño, corte, deslanado, limpieza de oídos y corte de uñas. Productos premium hipoalergénicos.',
    direccion: 'Av. Apoquindo 3456, Las Condes',
    comuna: 'Las Condes',
    telefono: '+56 9 8765 4321',
    wsp: '56987654321',
    web: 'www.groomingexpress.cl',
    instagram: 'grooming_express',
    facebook: 'GroomingExpressCL',
    horario: 'Lun–Sáb 9:00–18:00',
    promociones: [
      { id: 1, titulo: 'Baño + corte desde $9.990', descripcion: 'Precio especial para razas pequeñas. Consultar por razas medianas y grandes.' },
    ],
  },
  {
    id: 4,
    tipo: 'Tienda',
    nombre: 'PetShop Central',
    descripcion: 'Tienda especializada en alimentos premium, accesorios, juguetes, ropa y artículos de higiene para todo tipo de mascotas. Asesoría nutricional gratuita.',
    direccion: 'Irarrázaval 890, Ñuñoa',
    comuna: 'Ñuñoa',
    telefono: '+56 2 2456 7890',
    wsp: '56924567890',
    web: 'www.petshopcentral.cl',
    instagram: 'petshop_central',
    facebook: 'PetShopCentralCL',
    horario: 'Lun–Sáb 10:00–20:00 · Dom 11:00–18:00',
    promociones: [
      { id: 1, titulo: 'Alimento premium 2x1', descripcion: 'Válido en marcas seleccionadas de alimento seco para perros y gatos.' },
      { id: 2, titulo: 'Envío gratis sobre $30.000', descripcion: 'Despacho a domicilio sin costo en compras que superen los $30.000.' },
    ],
  },
  {
    id: 5,
    tipo: 'Veterinaria',
    nombre: 'Veterinaria Las Flores',
    descripcion: 'Atención veterinaria integral con enfoque en medicina preventiva. Servicio de vacunación, desparasitación, ecografía y odontología veterinaria.',
    direccion: 'Av. Vicuña Mackenna 2100, La Florida',
    comuna: 'La Florida',
    telefono: '+56 9 6543 2109',
    wsp: '56965432109',
    web: 'www.vetlasflores.cl',
    instagram: 'vetlasflores',
    facebook: 'VetLasFlores',
    horario: 'Lun–Vie 10:00–18:30 · Sáb 10:00–13:00',
    promociones: [],
  },
  {
    id: 6,
    tipo: 'Peluquería',
    nombre: 'PetHotel & Spa',
    descripcion: 'Spa y guardería para mascotas. Servicios de baño relajante, aromaterapia, masajes y hospedaje de calidad para cuando necesites salir de viaje.',
    direccion: 'Av. Vitacura 4321, Vitacura',
    comuna: 'Vitacura',
    telefono: '+56 9 7654 3210',
    wsp: '56976543210',
    web: 'www.pethotelspa.cl',
    instagram: 'pethotel_spa',
    facebook: 'PetHotelSpaCL',
    horario: 'Lun–Dom 8:00–20:00',
    promociones: [
      { id: 1, titulo: 'Guardería nocturna $15.990/noche', descripcion: 'Incluye cena, desayuno y paseo matutino. Cupos limitados, reserva con anticipación.' },
    ],
  },
  {
    id: 7,
    tipo: 'Urgencia 24/7',
    nombre: 'VetUrgencias Maipú',
    descripcion: 'Clínica de urgencias veterinarias en el sector poniente de Santiago. Atención inmediata, rayos X, laboratorio en línea y hospitalización.',
    direccion: 'Av. 5 de Abril 678, Maipú',
    comuna: 'Maipú',
    telefono: '+56 2 2111 2222',
    wsp: '56921112222',
    web: 'www.veturgenciasmaipú.cl',
    instagram: 'veturgencias_maipu',
    facebook: 'VetUrgenciasMaipu',
    horario: 'Abierto 24/7 todos los días',
    promociones: [],
  },
  {
    id: 8,
    tipo: 'Tienda',
    nombre: 'Mundo Mascota',
    descripcion: 'Gran variedad de productos para todo tipo de mascotas: perros, gatos, aves, reptiles y peces. Contamos con acuarios, jaulas y terrarios a medida.',
    direccion: 'Alameda 3456, Santiago Centro',
    comuna: 'Santiago Centro',
    telefono: '+56 2 2333 4444',
    wsp: '56923334444',
    web: 'www.mundomascota.cl',
    instagram: 'mundo_mascota_cl',
    facebook: 'MundoMascotaChile',
    horario: 'Lun–Sáb 9:30–19:30 · Dom 11:00–17:00',
    promociones: [
      { id: 1, titulo: 'Accesorios con 25% off', descripcion: 'Descuento en correas, arneses y camas seleccionadas. Válido hasta agotar stock.' },
    ],
  },
]
